version: '3.5'

services:

  reverse_proxy:
    image: nginx:1.21.4
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./conf/reverse_proxy/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxynet


networks:
  proxynet:
    name: custom_network
