---
- hosts: all
  vars:
    - user: '{{ ansible_user_id }}'
  #become: true # makes me root
  vars_files:
    - vars/default.yml

  tasks:
    - name: Sync Up Project
      synchronize:
        src: "{{ project_path }}"
        dest: "~/projects/"
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"
          - '--filter=:- .gitignore'

    - name: Configure front reverse proxy
      ansible.builtin.shell: './env/bin/python3 init.py projects'
      register: output
      become: true

    - name: Create .env
      ansible.builtin.shell: 'cd ~/projects/{{ project_name }}/ && (test -f scripts/setup_env.sh && ./scripts/setup_env.sh || true)'
      args:
        creates: "~/projects/{{ project_name }}/.env"
      register: output

    - name: Run docker-compose up of front proxy and every project
      ansible.builtin.shell: './up.sh'
      register: output
